sudo: false

os: osx

osx_image: xcode10.2

language: node_js

node_js:
  - lts/*

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn lint
  - yarn build:all --publish onTag
