# https://www.electron.build/multi-platform-build
# https://www.mokkapps.de/blog/run-automated-electron-app-tests-using-travis-ci/
# https://juejin.im/entry/5995599a6fb9a0249f6a131b

sudo: false

os: osx

osx_image: xcode10.2

language: node_js

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

node_js:
  - lts/*

cache:
  yarn: true
  directories:
    - node_modules
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE


notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn lint
  - yarn build:all --publish onTag
